version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./application/index.html:/usr/share/nginx/html/index.html
      - ./application/styles.css:/usr/share/nginx/html/styles.css